name: "Deploy on AWS"

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Execute deploy
        env:
          LAMBDA_ROLE: ${{ secrets.LAMBDA_ROLE }}
        run: ./deploy.sh